name: iOS Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and run tests
        env:
          PROJECT_NAME: GA-Example
          SCHEME_NAME: GA-Example
        run: |
          echo "Step 1"
          xcrun xctrace list devices
          echo "====================" &&
          echo "Step 2"
          xcrun xctrace list devices 2&>1 | grep -oE 'iPhone.*?[^\(]+'
          echo "====================" 

          device=$(xcrun xctrace list devices 2&>1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//")
          echo "Selected device: $device"

          xcodebuild test \
            -project ${{ env.PROJECT_NAME }}.xcodeproj \
            -scheme ${{ env.SCHEME_NAME }} \
            -sdk iphonesimulator \
            -destination "platform=iOS Simulator,name=$device" \
            -enableCodeCoverage YES CODE_SIGNING_REQUIRED=NO \
          | xcpretty && exit ${PIPESTATUS[0]}
