name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  env: 
    PROJECT_NAME: GA-Example
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up destination
        run: |
          name=$(xcrun simctl list devices | grep -oE 'iPhone.*?[^\(]+' | tail -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//")
          echo "DESTINATION_NAME=$device" >> $GITHUB_ENV
          echo "DESTINATION_PLATFORM=platform" >> $GITHUB_ENV

      - name: Build
        env:
          SCHEME_NAME: GA-Example
        run: |
          xcodebuild clean build \
            -project ${{ env.PROJECT_NAME }}.xcodeproj \
            -scheme ${{ env.SCHEME_NAME }} \
            -sdk iphoneos
          | xcpretty --color && exit ${PIPESTATUS[0]}

      - name: Test
        env:
          SCHEME_NAME: GA-Example
        run: |
          xcodebuild clean test \
            -project ${{ env.PROJECT_NAME }}.xcodeproj \
            -scheme ${{ env.SCHEME_NAME }} \
            -sdk iphonesimulator \
            -destination "platform=${{ env.DESTINATION_PLATFORM }},name=${{ env.DESTINATION_NAME }}" \
            -enableCodeCoverage YES \
          | xcpretty --color && exit ${PIPESTATUS[0]}
