name: iOS Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up destination
        env:
          DESTINATION_PLATFORM: iOS Simulator
        run: |
          device=$(xcrun simctl list devices | grep -oE 'iPhone.*?[^\(]+' | tail -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//")
          echo "Selected device: $device"
          echo "DESTINATION_NAME=$(device)"
          echo "DESTINATION_NAME=$(device)" >> $GITHUB_ENV
          echo "Selected device: ${{ env.DESTINATION_NAME }}"

      - name: Build and run tests
        env:
          PROJECT_NAME: GA-Example
          SCHEME_NAME: GA-Example
        run: |
          xcodebuild test \
            -project ${{ env.PROJECT_NAME }}.xcodeproj \
            -scheme ${{ env.SCHEME_NAME }} \
            -sdk iphonesimulator \
            -destination "platform=${{ env.DESTINATION_PLATFORM }},name=${{ env.DESTINATION_NAME }}" \
            -enableCodeCoverage YES CODE_SIGNING_REQUIRED=NO \
          | xcpretty && exit ${PIPESTATUS[0]}
