name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: macos-latest

    env: 
      PROJECT_NAME: GA-Example

    steps:
      - name: Checkout code
        id: checkout_code
        uses: actions/checkout@v3

      - name: Set up destination
        id: set_up_destination
        run: |
          name=$(xcrun simctl list devices | grep -oE 'iPhone.*?[^\(]+' | tail -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//")
          echo "DESTINATION_NAME=$device" >> $GITHUB_ENV
          echo "DESTINATION_PLATFORM=iOS Simulator" >> $GITHUB_ENV

      - name: Build
        id: build
        env:
          SCHEME_NAME: GA-Example
        run: |
          xcodebuild clean build CODE_SIGNING_REQUIRED=NO \
            -project ${{ env.PROJECT_NAME }}.xcodeproj \
            -scheme ${{ env.SCHEME_NAME }} \
            -sdk iphoneos
            -destination "platform=${{ env.DESTINATION_PLATFORM }},name=${{ env.DESTINATION_NAME }}" \
          | xcpretty --color && exit ${PIPESTATUS[0]}

      - name: Test
        id: test
        env:
          SCHEME_NAME: GA-Example
        run: |
          xcodebuild clean test \
            -project ${{ env.PROJECT_NAME }}.xcodeproj \
            -scheme ${{ env.SCHEME_NAME }} \
            -sdk iphonesimulator \
            -destination "platform=${{ env.DESTINATION_PLATFORM }},name=${{ env.DESTINATION_NAME }}" \
            -enableCodeCoverage YES \
          | xcpretty --color && exit ${PIPESTATUS[0]}
