name: iOS Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Select iOS simulator
        run: |
          device=$(xcrun xctrace list devices 2>&1 \
          | grep -oE 'iPhone.*?[^\(]+' \
          | head -1 \
          | awk '{$1=$1;print}' \
          | sed -e "s/ Simulator$//")

          echo "DESTIONATION_PLATFORM='iOS Simulator'" >> $GITHUB_ENV
          echo "DESTIONATION_NAME=$device" >> $GITHUB_ENV

      - name: Build and run tests
        env:
          PROJECT_NAME: GA-Example
          SCHEME_NAME: GA-Example
        run: |
          xcodebuild test \
            -project ${{ env.PROJECT_NAME }}.xcodeproj \
            -scheme ${{ env.SCHEME_NAME }} \
            -sdk iphonesimulator \
            -destination 'platform=${{ env.DESTIONATION_PLATFORM }},name=${{ env.DESTIONATION_NAME }}' \
            -enableCodeCoverage YES CODE_SIGNING_REQUIRED=NO \
          | xcpretty && exit ${PIPESTATUS[0]}
